#jpa 设置
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: xy@123456
    url: jdbc:mysql://localhost:3306/house?charset=utf8mb4&useSSL=false


#  session:

#    store-type: hash_map


logging:
  level:
    org :
      hirbernate:
        SQL: debug
  #关闭http
security:
  basic:
    enabled: false




